<?php
global $wo, $sqlConnect;
$root=$_SERVER['DOCUMENT_ROOT'];
require_once($root.'/config.php');
require_once('assets/init.php');

$user_id = $wo['user']['user_id'];

$userrole = Wo_UserRole($user_id);

if(isset($_POST['action']) && $_POST['action']=="downgrade_package" ) {

	$planid = $_POST['planid'];
	$subid = $_POST['subid'];
	$itemid = $_POST['itemid'];

	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();

	curl_setopt($ch, CURLOPT_URL, 'https://api.stripe.com/v1/subscriptions/'.$subid);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_POSTFIELDS, "cancel_at_period_end=false&items[0][id]=".$itemid."&items[0][plan]=".$planid);
	curl_setopt($ch, CURLOPT_POST, 1);
	curl_setopt($ch, CURLOPT_USERPWD, 'sk_live_0JbozWMwoKfQJJ2elLo33wNA' . ':' . '');

	$headers = array();
	$headers[] = 'Content-Type: application/x-www-form-urlencoded';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

	$result = curl_exec($ch);
	if (curl_errno($ch)) {
	    echo 'Error:' . curl_error($ch);
	}
	curl_close ($ch);

	$response = json_decode($result);



	$newesarr = array();
    if($response->status=="active") {

        
        try {
            
            $subscriptionid =  $response->id;
            $planid = $response->items->data[0]->plan->id;
            $planstartdate = date("Y-m-d H:i:s",$response->current_period_start);
            $renewdate = date("Y-m-d H:i:s",$response->current_period_end);

            $item_id = $response->items->data[0]->id;

            $packagetype = "";

            $packageid = "";

            switch ($planid) {
                case ULTIMATE_PACKAGE_ID:  // ultimate
                    $packageid = 4;
                    break;
                case VIP_PACKAGE_ID:  //vip
                    $packageid = 5;
                    break;

                case PRO_PACKAGE_ID:  //pro
                    $packageid = 3;
                    break;

                default:
                    # code...
                    break;
            }
            
            $customerid = $response->customer;
            $newesarr['packageid2'] = $packageid;
            $Packageinfoquery = mysqli_query($sqlConnect, "SELECT stastic_point FROM `Wo_Package_permission` WHERE `id` = '{$packageid}'");
            $Packagedata   = mysqli_fetch_assoc($Packageinfoquery);


            $Strasticpoints = $Packagedata['stastic_point'];
            $pro_type = $packageid;
            $pro_time = strtotime(date("Y-m-d H:i:s"));

            $amount = $response->plan->amount;
            $amount = $amount/100;
           
           	$userid = $user_id; 


            $Userquery = mysqli_query($sqlConnect, "UPDATE " . T_USERS . " SET is_pro='1', points=".$Strasticpoints.", pro_type='".$pro_type."', pro_time=".$pro_time." WHERE user_id=".$userid);

            $next_payment_date = date("Y-m-d",$response->current_period_end);

            $type = "monthly_price";

            $date  = date('n') . '/' . date("Y");
            $query1 = mysqli_query($sqlConnect, "INSERT INTO " . T_PAYMENTS . " (`user_id`, `amount`, `date`, `type`) VALUES ({$userid}, {$amount}, '{$date}', '{$type}')");

            $date  = date("Y-m-d H:i:s");
            $query2 = mysqli_query($sqlConnect, "INSERT INTO  `Wo_Payment_Transactions` (`userid`, `amount`, `transaction_dt`, `kind`,`notes`) VALUES ({$userid}, {$amount}, '{$date}', '".ucwords($packagetype)."','Upgrade')");

            $query3 = mysqli_query($sqlConnect, "INSERT INTO `Wo_Package_upgrade_transactions` (`user_id`, `price`,`transaction_date`, `package_id`, `transaction_id`,`next_payment_date`) VALUES ({$userid}, {$amount}, '{$date}', '".$packageid."','{$subscriptionid}','{$next_payment_date}')");

         	$subscriptiondelete = mysqli_query($sqlConnect, "UPDATE `Wo_user_subscription_details` SET status=0 WHERE `user_id`=".$userid." AND `subcription_id`='{$subid}'");

            $query4 = mysqli_query($sqlConnect, "INSERT INTO `Wo_user_subscription_details` (`user_id`, `subcription_id`,`customer_id`,`plan_id`,`item_id`, `plan_start_date`, `next_payment_date`,`created_date`,`modified_date`,`status`) VALUES ({$userid},'{$subscriptionid}','{$customerid}', '{$planid}','{$item_id}','{$planstartdate}','{$renewdate}','{$planstartdate}','{$planstartdate}',1)");


            $newesarr['stastic_point'] = $Strasticpoints;
            $newesarr['pro_type'] = $pro_type;
            $newesarr['pro_time'] = $pro_time;
            $newesarr['amount'] = $amount;
            $newesarr['type'] = $type;

        }
        
        //catch exception
        catch(Exception $e) {
          $newesarr['Error'] = $e->getMessage();
          $mysqli = mysqli_query($sqlConnect, "INSERT INTO `send_owl_responses` VALUES ('','false','".json_encode($newesarr)."')");
          print_r($newesarr);
        }
        
        // @header("location:".$wo['config']['site_url']);
    } 



}


if(isset($_POST['action']) && $_POST['action']=="upgrade_package" ) {

	$planid = $_POST['planid'];
	$subid = $_POST['subid'];
	$itemid = $_POST['itemid'];

	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();

	curl_setopt($ch, CURLOPT_URL, 'https://api.stripe.com/v1/subscriptions/'.$subid);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_POSTFIELDS, "cancel_at_period_end=false&items[0][id]=".$itemid."&items[0][plan]=".$planid);
	curl_setopt($ch, CURLOPT_POST, 1);
	curl_setopt($ch, CURLOPT_USERPWD, 'sk_live_0JbozWMwoKfQJJ2elLo33wNA' . ':' . '');

	$headers = array();
	$headers[] = 'Content-Type: application/x-www-form-urlencoded';
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

	$result = curl_exec($ch);
	if (curl_errno($ch)) {
	    echo 'Error:' . curl_error($ch);
	}
	curl_close ($ch);
/*	error_reporting(E_ALL);
	ini_set("display_errors",1);*/
	

	$response = json_decode($result);

    /*echo "<pre>";
        print_r($response);
    echo "<pre>";*/
	$newesarr = array();
    if($response->status=="active") {

        
        try {
            
            $subscriptionid =  $response->id;
            $planid = $response->items->data[0]->plan->id;
            $planstartdate = date("Y-m-d H:i:s",$response->current_period_start);
            $renewdate = date("Y-m-d H:i:s",$response->current_period_end);

            $item_id = $response->items->data[0]->id;
            $packagetype = "";

            $packageid = "";

           /* switch ($planid) {
                case 'plan_Eoj2DVoLZLcRFE':
                    $packageid = 4;
                    break;
                case 'plan_Eoj2w90UlJcC7X':
                    $packageid = 5;
                    break;

                case 'plan_Eoj1tj6RF2xIfk':
                    $packageid = 3;
                    break;

                default:
                    # code...
                    break;
            }*/

            switch ($planid) {
                case ULTIMATE_PACKAGE_ID:  // ultimate
                    $packageid = 4;
                    break;
                case VIP_PACKAGE_ID :  //vip
                    $packageid = 5;
                    break;

                case PRO_PACKAGE_ID :  //pro
                    $packageid = 3;
                    break;

                default:
                    # code...
                    break;
            }
            
            $customerid = $response->customer;

            $newesarr['packageid2'] = $packageid;
            $Packageinfoquery = mysqli_query($sqlConnect, "SELECT stastic_point FROM `Wo_Package_permission` WHERE `id` = '{$packageid}'");
            $Packagedata   = mysqli_fetch_assoc($Packageinfoquery);


            $Strasticpoints = $Packagedata['stastic_point'];
            $pro_type = $packageid;
            $pro_time = strtotime(date("Y-m-d H:i:s"));

            $amount = $response->plan->amount;
            $amount = $amount/100;

           	$userid = $user_id; 
        	

            /************************** Refferal Commission ****************************/

            $refferalid = Wo_get_refferal_id($userid);
            if ($refferalid!=0 && $wo['config']['affiliate_system'] == 1 && $wo['config']['affiliate_type'] == 0) {
                $ref_user_id = $refferalid;
                if (!empty($ref_user_id) && is_numeric($ref_user_id)) {
                    /*$update_user    = Wo_UpdateUserData($wo['user']['user_id'], array(
                        'referrer' => $ref_user_id,
                        'src' => 'Referrer'
                    ));*/
                    $update_balance = Wo_UpdateBalance($ref_user_id, $wo['config']['amount_ref']);
                    //unset($_SESSION['ref']);
                }
            }
            //record affiliate with percentage
            if ($refferalid!=0 && $wo['config']['affiliate_system']==1 && $wo['config']['affiliate_type'] == 1) {
                if ($wo['config']['amount_percent_ref'] > 0) {
                    $ref_user_id = $refferalid;
                    if (!empty($ref_user_id) && is_numeric($ref_user_id)) {
                    
                        $ref_amount     = ($wo['config']['amount_percent_ref'] * $amount) / 100;
                        $update_balance = Wo_UpdateBalance($ref_user_id, $ref_amount);
                        //unset($_SESSION['ref']);
                    }
                } else if ($wo['config']['amount_ref'] > 0) {
                    $ref_user_id = Wo_UserIdFromUsername($_SESSION['ref']);
                    if (!empty($ref_user_id) && is_numeric($ref_user_id)) {
                        $update_user    = Wo_UpdateUserData($wo['user']['user_id'], array(
                            'referrer' => $ref_user_id,
                            'src' => 'Referrer'
                        ));
                        $update_balance = Wo_UpdateBalance($ref_user_id, $wo['config']['amount_ref']);
                        //unset($_SESSION['ref']);
                    }
                }
            }

            

            $Userquery = mysqli_query($sqlConnect, "UPDATE " . T_USERS . " SET is_pro='1', points=".$Strasticpoints.", pro_type='".$pro_type."', pro_time=".$pro_time." WHERE user_id=".$userid);

            $next_payment_date = date("Y-m-d",$response->current_period_end);


            

            $type = "monthly_price";

            $date  = date('n') . '/' . date("Y");
            $query1 = mysqli_query($sqlConnect, "INSERT INTO " . T_PAYMENTS . " (`user_id`, `amount`, `date`, `type`) VALUES ({$userid}, {$amount}, '{$date}', '{$type}')");

            $date  = date("Y-m-d H:i:s");
            $query2 = mysqli_query($sqlConnect, "INSERT INTO  `Wo_Payment_Transactions` (`userid`, `amount`, `transaction_dt`, `kind`,`notes`) VALUES ({$userid}, {$amount}, '{$date}', '".ucwords($packagetype)."','Upgrade')");

            $query3 = mysqli_query($sqlConnect, "INSERT INTO `Wo_Package_upgrade_transactions` (`user_id`, `price`,`transaction_date`, `package_id`, `transaction_id`,`next_payment_date`) VALUES ({$userid}, {$amount}, '{$date}', '".$packageid."','{$subscriptionid}','{$next_payment_date}')");

         	$subscriptiondelete = mysqli_query($sqlConnect, "UPDATE `Wo_user_subscription_details` SET status=0 WHERE user_id=".$userid);


            $query4 = mysqli_query($sqlConnect, "INSERT INTO `Wo_user_subscription_details` (`user_id`, `subcription_id`,`customer_id`,`plan_id`,`item_id`, `plan_start_date`, `next_payment_date`,`created_date`,`modified_date`,`status`) VALUES ({$userid},'{$subscriptionid}','{$customerid}', '{$planid}','{$item_id}','{$planstartdate}','{$renewdate}','{$planstartdate}','{$planstartdate}',1)");



            $newesarr['stastic_point'] = $Strasticpoints;
            $newesarr['pro_type'] = $pro_type;
            $newesarr['pro_time'] = $pro_time;
            $newesarr['amount'] = $amount;
            $newesarr['type'] = $type;

            
/*            $mysqli = mysqli_query($sqlConnect, "INSERT INTO `send_owl_responses` VALUES ('','".$responsetype."','".json_encode($newesarr)."')");*/
        }
        
        //catch exception
        catch(Exception $e) {
          $newesarr['Error'] = $e->getMessage();
          $mysqli = mysqli_query($sqlConnect, "INSERT INTO `send_owl_responses` VALUES ('','false','".json_encode($newesarr)."')");
          print_r($newesarr);
        }
        
        // @header("location:".$wo['config']['site_url']);
    }  else {

        echo $response->error->message;
    }

}


die;

?>