<?php

global $wo, $sqlConnect;
$root=$_SERVER['DOCUMENT_ROOT'];
require_once($root.'/config.php');
require_once('assets/init.php');

/*error_reporting(E_ALL);

ini_set("display_errors",1);*/
$Packageinfoquery = mysqli_query($sqlConnect, "SELECT * FROM `Wo_user_subscription_details` WHERE `status` = 1");

while($row = mysqli_fetch_assoc($Packageinfoquery)) {
    
/*    echo "<pre>";
		print_r($row);
	echo "</pre>";*/
    $subscriptionid = $row['subcription_id'];
    $customer_id = $row['customer_id'];
    $plan_id = $row['plan_id'];
    $item_id = $row['item_id'];
    $plan_start_date = $row['plan_start_date'];
    $next_payment_date = $row['next_payment_date'];
    $status = $row['status'];
    $userid = $row['user_id'];

   /* echo $currentdatetimestamp = strtotime(date("Y-m-d H:i:s"));
    echo "<br>";
    echo $next_payment_datetimstamp = strtotime($next_payment_date);*/
    
    if($currentdatetimestamp > $next_payment_datetimstamp) {

            // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
            $ch = curl_init();

            curl_setopt($ch, CURLOPT_URL, 'https://api.stripe.com/v1/subscriptions/'.$subscriptionid);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');

            curl_setopt($ch, CURLOPT_USERPWD, 'sk_live_0JbozWMwoKfQJJ2elLo33wNA' . ':' . '');

            $result = curl_exec($ch);
            if (curl_errno($ch)) {
                echo 'Error:' . curl_error($ch);
            }
            curl_close ($ch);

            $response = json_decode( $result);


            if($response->status=="active") {


                try {

                    $planid = $response->items->data[0]->plan->id;
                    $planstartdate = date("Y-m-d H:i:s",$response->current_period_start);
                    $renewdate = date("Y-m-d H:i:s",$response->current_period_end);
                    $item_id = $response->items->data[0]->id;



                    switch ($planid) {
                        case 'plan_Eoj2DVoLZLcRFE':
                            $packageid = 4;
                            break;
                        case 'plan_Eoj2w90UlJcC7X':
                            $packageid = 5;
                            break;

                        //case 'plan_Eoj1tj6RF2xIfk':
                        case 'plan_EpXfQQHCtUw0Pc':   // Testing purpose plan id
                        
                            $packageid = 3;
                            break;

                        default:
                            # code...
                            break;
                    }
        
                    $Packageinfoquery = mysqli_query($sqlConnect, "SELECT stastic_point FROM `Wo_Package_permission` WHERE `id` = '{$packageid}'");
                    $Packagedata   = mysqli_fetch_assoc($Packageinfoquery);


                    $Strasticpoints = $Packagedata['stastic_point'];

                    $Userpoints = Wo_GetUserSingleColumn("points","user_id",$userid);
                    $totalpoints = $Userpoints +  $Strasticpoints;

                    $query1 = mysqli_query($sqlConnect, "UPDATE `Wo_Users` SET points='{$totalpoints}' WHERE user_id=".$userid);
        

                    $next_payment_date = date("Y-m-d",$response->current_period_end);


                   	$query4 = mysqli_query($sqlConnect, "UPDATE `Wo_user_subscription_details` SET plan_start_date='{$planstartdate}',`next_payment_date`='$renewdate',`modified_date`='$planstartdate' WHERE subcription_id='{$subscriptionid}'");


                    $amount = $response->plan->amount;

                    $amount = $amount/100;

                    /************************** Refferal Commission ****************************/

                    $refferalid = Wo_get_refferal_id($userid);
                    if ($refferalid!=0 && $wo['config']['affiliate_system'] == 1 && $wo['config']['affiliate_type'] == 0) {
                        $ref_user_id = $refferalid;
                        if (!empty($ref_user_id) && is_numeric($ref_user_id)) {
                            /*$update_user    = Wo_UpdateUserData($wo['user']['user_id'], array(
                                'referrer' => $ref_user_id,
                                'src' => 'Referrer'
                            ));*/
                            $update_balance = Wo_UpdateBalance($ref_user_id, $wo['config']['amount_ref']);
                            //unset($_SESSION['ref']);
                        }
                    }
                    //record affiliate with percentage
                    if ($refferalid!=0 && $wo['config']['affiliate_system']==1 && $wo['config']['affiliate_type'] == 1) {
                        if ($wo['config']['amount_percent_ref'] > 0) {
                            $ref_user_id = $refferalid;
                            if (!empty($ref_user_id) && is_numeric($ref_user_id)) {
                            
                                $ref_amount     = ($wo['config']['amount_percent_ref'] * $amount) / 100;
                                $update_balance = Wo_UpdateBalance($ref_user_id, $ref_amount);
                                //unset($_SESSION['ref']);
                            }
                        } else if ($wo['config']['amount_ref'] > 0) {
                            $ref_user_id = Wo_UserIdFromUsername($_SESSION['ref']);
                            if (!empty($ref_user_id) && is_numeric($ref_user_id)) {
                                $update_user    = Wo_UpdateUserData($wo['user']['user_id'], array(
                                    'referrer' => $ref_user_id,
                                    'src' => 'Referrer'
                                ));
                                $update_balance = Wo_UpdateBalance($ref_user_id, $wo['config']['amount_ref']);
                                //unset($_SESSION['ref']);
                            }
                        }
                    }


        
                }
                
                //catch exception
                catch(Exception $e) {
                  $newesarr['Error'] = $e->getMessage();
                  $mysqli = mysqli_query($sqlConnect, "INSERT INTO `send_owl_responses` VALUES ('','false','".json_encode($newesarr)."')");
                  print_r($newesarr);
                }

            } else {

            	$query1 = mysqli_query($sqlConnect, "UPDATE `Wo_Users` SET pro_type=2 WHERE user_id=".$userid);

                Wo_delete_twilio_number($userid);
                
            	$query4 = mysqli_query($sqlConnect, "UPDATE `Wo_user_subscription_details` SET status=0 WHERE subcription_id='{$subscriptionid}'");

            }



    }
    
}

die;
?>